CXXFLAGS +=
CXXFLAGS +=
CXXFLAGS +=
CXXFLAGS += -I/opt/ros/foxy/include
LIBS +=
LIBS += 
LIBS += 
LIBS += 
LIBS += 


LIBS += /opt/ros/foxy/lib/librviz_common.so
LIBS += /opt/ros/foxy/lib/librclcpp.so
LIBS += /opt/ros/foxy/lib/librcutils.so
LIBS += /opt/ros/foxy/opt/rviz_ogre_vendor/lib/libOgreMain.so.1.12.1
LIBS += /opt/ros/foxy/lib/librviz_rendering.so
LIBS += /opt/ros/foxy/opt/yaml_cpp_vendor/lib/libyaml-cpp.so.0.6
LIBS += /opt/ros/foxy/lib/libresource_retriever.so
LIBS += /opt/ros/foxy/lib/librcl.so
LIBS += /opt/ros/foxy/lib/libament_index_cpp.so
LIBS += /opt/ros/foxy/lib/libclass_loader.so
LIBS += /opt/ros/foxy/lib/librcpputils.so
LIBS += /opt/ros/foxy/lib/x86_64-linux-gnu/libconsole_bridge.so.1.0
LIBS += /opt/ros/foxy/lib/liblibstatistics_collector.so
LIBS += /opt/ros/foxy/lib/librcl_yaml_param_parser.so
LIBS += /opt/ros/foxy/lib/librosgraph_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libstatistics_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libtracetools.so
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librmw_implementation.so
LIBS += /opt/ros/foxy/lib/librmw.so
LIBS += /opt/ros/foxy/opt/rviz_ogre_vendor/lib/libOgreOverlay.so.1.12.1
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_typesupport_c.so
LIBS += /opt/ros/foxy/lib/librcl_logging_spdlog.so
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_generator_c.so
LIBS += /opt/ros/foxy/lib/librosidl_runtime_c.so
LIBS += /opt/ros/foxy/lib/libyaml.so
LIBS += /opt/ros/foxy/lib/librosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librosidl_typesupport_c.so
LIBS += /opt/ros/foxy/lib/libbuiltin_interfaces__rosidl_generator_c.so

LIBS += /opt/ros/foxy/lib/libstd_srvs__python.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_generator_c.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_c.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_connext_c.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_connext_cpp.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_fastrtps_c.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_fastrtps_cpp.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_introspection_c.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_introspection_cpp.so

all:
	g++ ${CXXFLAGS} test.cc -o test ${LIBS}

