######################################################################
# Automatically generated by qmake (3.1) Sat Dec 21 15:06:19 2024
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QMAKE_CXXFLAGS +=
QMAKE_CXXFLAGS += -I/opt/ros/foxy/include

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += CameraPanel.hh
SOURCES += CameraPanel.cc test.cc
QT += core widgets network
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 
LIBS += 

LIBS += /opt/ros/foxy/lib/librviz_common.so
LIBS += /opt/ros/foxy/lib/libdiagnostic_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libactionlib_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libcv_bridge.so
LIBS += /opt/ros/foxy/lib/librclcpp.so
LIBS += /opt/ros/foxy/lib/libsensor_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librviz_rendering.so
LIBS += /opt/ros/foxy/opt/rviz_ogre_vendor/lib/libOgreOverlay.so.1.12.1
LIBS += /opt/ros/foxy/opt/rviz_ogre_vendor/lib/libOgreMain.so.1.12.1
LIBS += /opt/ros/foxy/lib/libclass_loader.so
LIBS += /opt/ros/foxy/lib/x86_64-linux-gnu/libconsole_bridge.so.1.0
LIBS += /opt/ros/foxy/lib/libgeometry_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/liblibstatistics_collector.so
LIBS += /opt/ros/foxy/lib/librcl.so
LIBS += /opt/ros/foxy/lib/libstatistics_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libtracetools.so
LIBS += /opt/ros/foxy/lib/libstd_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/libstd_srvs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librcutils.so
LIBS += /opt/ros/foxy/opt/yaml_cpp_vendor/lib/libyaml-cpp.so.0.6
LIBS += /opt/ros/foxy/lib/libresource_retriever.so
LIBS += /opt/ros/foxy/lib/libament_index_cpp.so
LIBS += /opt/ros/foxy/lib/librcpputils.so
LIBS += /opt/ros/foxy/lib/librosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librcl_yaml_param_parser.so
LIBS += /opt/ros/foxy/lib/librosgraph_msgs__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_typesupport_cpp.so
LIBS += /opt/ros/foxy/lib/librmw_implementation.so
LIBS += /opt/ros/foxy/lib/librmw.so
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_typesupport_c.so
LIBS += /opt/ros/foxy/lib/librcl_logging_spdlog.so
LIBS += /opt/ros/foxy/lib/librcl_interfaces__rosidl_generator_c.so
LIBS += /opt/ros/foxy/lib/librosidl_runtime_c.so
LIBS += /opt/ros/foxy/lib/libyaml.so
LIBS += /opt/ros/foxy/lib/librosidl_typesupport_c.so
LIBS += /opt/ros/foxy/lib/libbuiltin_interfaces__rosidl_generator_c.so
LIBS += /opt/ros/foxy/lib/libzstd.so.1

